import type { CSSProperties } from 'react'

export const adminStyles: Record<string, CSSProperties> = {
  root: {
    position: 'relative',
    minHeight: '100dvh',
    background: 'var(--bg-base)',
    overflow: 'hidden',
  },
  mesh: {
    position: 'absolute',
    inset: 0,
    background: 'radial-gradient(ellipse 80% 40% at 60% -10%, rgba(120,88,255,.14) 0%, transparent 55%)',
    pointerEvents: 'none',
  },
  page: {
    position: 'relative',
    maxWidth: '1100px',
    margin: '0 auto',
    padding: '2rem 1.25rem 4rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.25rem',
  },
  header: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.5rem',
    marginBottom: '0.25rem',
  },
  backLink: {
    fontSize: '0.8rem',
    color: 'var(--text-dim)',
    textDecoration: 'none',
  },
  headerRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.875rem',
  },
  pageTitle: {
    margin: 0,
    fontSize: '1.6rem',
    fontWeight: 700,
    color: 'var(--text-primary)',
    letterSpacing: '-0.02em',
  },
  adminBadge: {
    padding: '2px 10px',
    borderRadius: 'var(--radius-full)',
    fontSize: '0.7rem',
    fontWeight: 700,
    letterSpacing: '0.08em',
    background: 'var(--purple-dim)',
    color: 'var(--purple-light)',
    border: '1px solid var(--purple-border)',
  },
  tabs: {
    display: 'flex',
    gap: '0.25rem',
    borderBottom: '1px solid var(--border-subtle)',
    marginBottom: '0.25rem',
  },
  tab: {
    padding: '0.65rem 1.125rem',
    background: 'none',
    border: 'none',
    borderBottom: '2px solid transparent',
    color: 'var(--text-dim)',
    fontSize: '0.875rem',
    fontWeight: 500,
    cursor: 'pointer',
    marginBottom: '-1px',
    transition: 'color 0.15s, border-color 0.15s',
  },
  tabActive: {
    color: 'var(--text-primary)',
    borderBottomColor: 'var(--purple)',
  },
  card: {
    background: 'rgba(26,25,36,.6)',
    border: '1px solid var(--border-base)',
    borderRadius: 'var(--radius-xl)',
    padding: '1.375rem 1.5rem',
    backdropFilter: 'blur(12px)',
    WebkitBackdropFilter: 'blur(12px)',
  },
  sectionTitle: {
    margin: '0 0 1rem',
    fontSize: '0.85rem',
    fontWeight: 600,
    color: 'var(--text-mid)',
    textTransform: 'uppercase',
    letterSpacing: '0.06em',
  },
  emptyText: {
    fontSize: '0.875rem',
    color: 'var(--text-muted)',
    padding: '0.5rem 0',
  },
}
